### ISSUE TITLE
Error Query Builder : throw a Fatal Error when use update method.

### ISSUE THREAD

**Issue by ammarfaizi2** [ammarfaizi2/icetea#12]
I tried updating a table with `DB::table('table_name')->where(...)->update(...)` but the result is a Fatal Error.
Any advice?

```
Fatal error: Uncaught Error: Call to undefined function System\Crayner\Database\makeUpdateParameter() in /home/redangel/public_html/newicetea/System/Crayner/Database/DB.php:385

Stack trace:
#0 /home/redangel/public_html/newicetea/App/Controllers/test.php(26): System\Crayner\Database\DB::update(Array)
#1 /home/redangel/public_html/newicetea/System/Crayner.php(71): App\Controllers\test->index()
#2 /home/redangel/public_html/newicetea/public/index.php(4): System\Crayner->run()
#3 {main}
 thrown in /home/redangel/public_html/newicetea/System/Crayner/Database/DB.php on line 385
```

Could you fix it and commit them to the branch dev2 ?
and please tell me that it done. Then I will merge it to the main branch. Thanks!

![eq](https://user-images.githubusercontent.com/26004054/27188700-3c093f86-5219-11e7-850f-f7e2df4fce62.png)
![wr](https://user-images.githubusercontent.com/26004054/27188705-3d96d11a-5219-11e7-8f82-ee381ae92725.png)

**Comment by arbiyanto** [comment]
#13
