### ISSUE TITLE
PR Welcome : Increment and Decrement method

### ISSUE THREAD

**Issue by ammarfaizi2** [ammarfaizi2/icetea#17]
How can i execute this query with querybuilder?
```UPDATE `register_history` SET try = try+1 WHERE hash = :hash```

Can you add increment and decrement method to querybuilder like laravel ?
It is a future challenge. I would welcome the PR.

![rw](https://user-images.githubusercontent.com/26004054/27227933-ca3a9b2c-52cf-11e7-848d-473e23e8428d.png)

**Comment by arbiyanto** [comment]
PR #18
