### ISSUE TITLE
Error Select, please solve huft...

### ISSUE THREAD

**Issue by ammarfaizi2** [ammarfaizi2/icetea#2]
commit 11fd19e68056f2bc7995812740f07fb5e7087b5e
Author: Ammar Faizi <ammarfaizi2@gmail.com>
Date:   Fri Jun 9 21:38:26 2017 +0700

    Update login model

![qwerqwer](https://user-images.githubusercontent.com/26004054/26980353-206aca04-4d5c-11e7-876c-12563b813d48.png)

![qwerqwer](https://user-images.githubusercontent.com/26004054/26980331-07703296-4d5c-11e7-8c83-7e92f51968bb.png)

**Comment by ammarfaizi2** [comment]
kalau misal mau select where berarti gimana?

**Comment by arbiyanto** [comment]
->table("users")->where("column",">=","value")
OR
->table("users")->where("column",,"value") // default equal operator '='

**Comment by ammarfaizi2** [comment]
[SOLVED]
![qwerqwer](https://user-images.githubusercontent.com/26004054/26981411-38b5dd8a-4d5f-11e7-997d-738f425908bf.png)
